apiVersion: v1
kind: Secret
metadata:
  name: azureblob-secret
type: Opaque
stringData:
  azurestorageaccountname: {{ .Values.nodebb.azure.accountName }}
  azurestorageaccountsastoken: {{ .Values.nodebb.azure.sasToken }}
