apiVersion: v1
kind: ConfigMap
metadata:
  name: nodebb-configmap
data:
  config.json: |
    {
      "url": {{ .Values.nodebb.config.url | quote }},
      "secret": {{ .Values.nodebb.config.secret | quote }},
      "database": "mongo",
      "mongo": {
        "uri": "mongodb://{{ .Values.mongodb.user | quote }}:{{ .Values.mongodb.password | quote }}@{{ .Values.mongodb.host | quote }}:{{ .Values.mongodb.port }}/{{ .Values.mongodb.database | quote }}?authSource={{ .Values.mongodb.authSource | quote }}"
      },
      "admin": {
        "username": {{ .Values.nodebb.config.admin.username | quote }},
        "password": {{ .Values.nodebb.config.admin.password | quote }},
        "email": {{ .Values.nodebb.config.admin.email | quote }}
      },
      "upload_path": "https://{{ .Values.nodebb.config.azure.accountName | quote }}.blob.core.windows.net/{{ .Values.nodebb.config.azure.containerName | quote }}/?{{ .Values.nodebb.config.azure.sasToken | quote }}"
    }
