apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-start-script-{{ .Values.tenant }}
data:
  mongo-start.sh: |
    #!/bin/bash
    echo "Starting mongod in background..."
    mongod --bind_ip_all &

    echo "Waiting for Mongo to become ready..."
    until mongosh --eval "db.adminCommand('ping')" > /dev/null 2>&1; do
      sleep 2
    done

    echo "Creating root user if not exists..."
    mongosh --eval '
      db = db.getSiblingDB("admin");
      if (!db.getUser("root")) {
        db.createUser({
          user: "root",
          pwd: "example",
          roles: [ { role: "root", db: "admin" } ]
        });
        print("Created root user.");
      } else {
        print("Root user already exists.");
      }
    '

    echo "Creating nodebb user if not exists..."
    mongosh --eval '
      db = db.getSiblingDB("nodebb");
      if (!db.getUser("{{ .Values.mongo.dbUser }}")) {
        db.createUser({
          user: "{{ .Values.mongo.dbUser }}",
          pwd: "{{ .Values.mongo.dbPass }}",
          roles: [ { role: "readWrite", db: "nodebb" } ]
        });
        print("Created nodebb user.");
      } else {
        print("NodeBB user already exists.");
      }

      print("Current users in nodebb:");
      printjson(db.getUsers());
    '

    echo "MongoDB ready. Tailing logs..."
    wait -n
