apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodebb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodebb
  template:
    metadata:
      labels:
        app: nodebb
    spec:
      containers:
        - name: nodebb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 4567
          env:
            - name: SETUP
              value: "{{ .Values.nodebb.setup | quote }}"
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: nodebb-secrets
                  key: mongodb-user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nodebb-secrets
                  key: mongodb-password
            - name: NODEBB_SECRET
              valueFrom:
                secretKeyRef:
                  name: nodebb-secrets
                  key: nodebb-secret
            - name: AZURE_SAS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: nodebb-secrets
                  key: azure-sas-token
          command:
            - /bin/sh
            - -c
            - |
              echo "Creating config.json..."
              cat <<EOF > /usr/src/app/config.json
              {
                "url": "{{ .Values.nodebb.config.url }}",
                "secret": "${NODEBB_SECRET}",
                "database": "mongo",
                "mongo": {
                  "uri": "mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@{{ .Values.mongodb.host }}:{{ .Values.mongodb.port }}/{{ .Values.mongodb.database }}?authSource={{ .Values.mongodb.authSource }}"
                },
                "admin": {
                  "username": "{{ .Values.nodebb.config.admin.username }}",
                  "password": "{{ .Values.nodebb.config.admin.password }}",
                  "email": "{{ .Values.nodebb.config.admin.email }}"
                },
                "upload_path": "https://{{ .Values.nodebb.config.azure.accountName }}.blob.core.windows.net/{{ .Values.nodebb.config.azure.containerName }}/?${AZURE_SAS_TOKEN}"
              }
              EOF

              if [ "$SETUP" = "true" ]; then
                ./nodebb setup --config=/usr/src/app/config.json
              else
                ./nodebb build || true
                ./nodebb start
              fi
