apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodebb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodebb
  template:
    metadata:
      labels:
        app: nodebb
    spec:
      containers:
        - name: nodebb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 4567
          env:
            - name: CONFIG_DIR
              value: "/opt/config"
            - name: CONFIG
              value: "/opt/config/config.json"
            - name: PACKAGE_MANAGER
              value: "npm"
            - name: START_BUILD
              value: "true"
          volumeMounts:
            - name: config-volume
              mountPath: /opt/config
            - name: build-volume
              mountPath: /usr/src/app/build
            - name: uploads-volume
              mountPath: /usr/src/app/public/uploads
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: nodebb-config
        - name: build-volume
          persistentVolumeClaim:
            claimName: nodebb-build
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: nodebb-uploads
