apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodebb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodebb
  template:
    metadata:
      labels:
        app: nodebb
    spec:
      containers:
        - name: nodebb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 4567
          command:
            - /bin/sh
            - -c
            - |
              echo "Creating config.json..."
              cat <<EOF > /usr/src/app/config.json
              {
                "url": "{{ .Values.nodebb.config.url }}",
                "secret": "{{ .Values.nodebb.config.secret }}",
                "database": "mongo",
                "mongo": {
                  "uri": "mongodb://{{ .Values.mongodb.user }}:{{ .Values.mongodb.password }}@{{ .Values.mongodb.host }}:{{ .Values.mongodb.port }}/{{ .Values.mongodb.database }}?authSource={{ .Values.mongodb.authSource }}"
                },
                "admin": {
                  "username": "{{ .Values.nodebb.config.admin.username }}",
                  "password": "{{ .Values.nodebb.config.admin.password }}",
                  "email": "{{ .Values.nodebb.config.admin.email }}"
                },
                "upload_path": "https://{{ .Values.nodebb.config.azure.accountName }}.blob.core.windows.net/{{ .Values.nodebb.config.azure.containerName }}/"
              }
              EOF
              ./nodebb build || true
              ./nodebb start
