apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodebb-uploads-{{ .Values.tenant }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.nodebb.uploadSize | default "2Gi" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodebb-config-{{ .Values.tenant }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.nodebb.configSize | default "100Mi" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodebb-{{ .Values.tenant }}
spec:
  selector:
    matchLabels:
      app: nodebb-{{ .Values.tenant }}
  template:
    metadata:
      labels:
        app: nodebb-{{ .Values.tenant }}
    spec:
      containers:
        - name: nodebb
          image: elestio/nodebb:latest
          ports:
            - containerPort: 4567
          env:
            - name: NODE_ENV
              value: production
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: nodebb-uploads-{{ .Values.tenant }}
        - name: config-volume
          persistentVolumeClaim:
            claimName: nodebb-config-{{ .Values.tenant }}
---
apiVersion: v1
kind: Service
metadata:
  name: nodebb-{{ .Values.tenant }}
spec:
  selector:
    app: nodebb-{{ .Values.tenant }}
  ports:
    - port: 80
      targetPort: 4567
  type: {{ .Values.service.type | default "LoadBalancer" }}
