apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodebb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodebb
  template:
    metadata:
      labels:
        app: nodebb
    spec:
      containers:
        - name: nodebb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 4567
          env:
            - name: CONFIG_DIR
              value: "/opt/config"                        # ✅ directory where config.json will be saved
            - name: CONFIG
              value: "/opt/config/config.json"            # ✅ full path to config.json
            - name: PACKAGE_MANAGER
              value: "npm"
            - name: START_BUILD
              value: "true"
          volumeMounts:
            - name: config-volume
              mountPath: /opt/config                      # ✅ this is where config.json will live
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: nodebb-config                      # make sure this PVC exists
