apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodebb-uploads-{{ .Values.tenant }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.nodebb.uploadSize | default "2Gi" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodebb-config-{{ .Values.tenant }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.nodebb.configSize | default "100Mi" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodebb-{{ .Values.tenant }}
spec:
  selector:
    matchLabels:
      app: nodebb-{{ .Values.tenant }}
  template:
    metadata:
      labels:
        app: nodebb-{{ .Values.tenant }}
    spec:
      initContainers:
        - name: init-config
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              echo "Restoring config.json if it exists..."
              if [ -f /mnt/config/config.json ]; then
                cp /mnt/config/config.json /usr/src/app/config.json
              fi
          volumeMounts:
            - name: config-volume
              mountPath: /mnt/config
      containers:
        - name: nodebb
          image: elestio/nodebb:latest
          ports:
            - containerPort: 4567
          env:
            - name: NODE_ENV
              value: production
          volumeMounts:
            - name: uploads
              mountPath: /usr/src/app/public/uploads
            - name: config-volume
              mountPath: /mnt/config
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    echo "Backing up config.json before shutdown..."
                    if [ -f /usr/src/app/config.json ]; then
                      cp /usr/src/app/config.json /mnt/config/config.json
                    fi
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: nodebb-uploads-{{ .Values.tenant }}
        - name: config-volume
          persistentVolumeClaim:
            claimName: nodebb-config-{{ .Values.tenant }}
---
apiVersion: v1
kind: Service
metadata:
  name: nodebb-{{ .Values.tenant }}
spec:
  selector:
    app: nodebb-{{ .Values.tenant }}
  ports:
    - port: 80
      targetPort: 4567
  type: {{ .Values.service.type | default "LoadBalancer" }}
