apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodebb-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.config.size }}
