apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodebb-uploads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.uploads.size }}
