apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-{{ .Values.tenant }}
spec:
  selector:
    matchLabels:
      app: redis-{{ .Values.tenant }}
  template:
    metadata:
      labels:
        app: redis-{{ .Values.tenant }}
    spec:
      containers:
        - name: redis
          image: redis:7
          args: ["redis-server", "--requirepass", "{{ .Values.redis.password }}"]
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-{{ .Values.tenant }}
spec:
  selector:
    app: redis-{{ .Values.tenant }}
  ports:
    - port: 6379
