apiVersion: v1
kind: Service
metadata:
  name: nodebb
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nodebb
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4567
      protocol: TCP
