apiVersion: v1
kind: Service
metadata:
  name: nodebb
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: nodebb
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: 4567

