image:
  repository: ghcr.io/pjanprinsloo/e2-nodebb
  tag: v1.0.6
  pullPolicy: Always

nodebb:
  setup: true
  config:
    url: "http://nodebb.localhost"
    secret: "mysecret" # fallback secret, will be injected via secret in actual deployment
    admin:
      username: "admin"
      password: "changeme"
      email: "admin@example.com"
    azure:
      accountName: "youraccount"
      containerName: "cxo-forum"
      sasToken: "?sp=..."

mongodb:
  host: "mongo.default.svc.cluster.local"
  port: 27017
  user: "cxo"
  password: "Hdfs#289!@#sjk1"
  database: "nodebb"
  authSource: "admin"

service:
  type: ClusterIP
  port: 80
